name: Publish Docker GPU

on:
  push:
    branches:
    - master
    tags:
    - v*
  
  # Triggered by ODM build (after docker push)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      OWNER: wmobley
      IMAGE_NAME: ghcr.io/wmobley/nodeodm
      BASE_ODM_IMAGE: ghcr.io/wmobley/odm:gpu
      GHCR_TOKEN: ${{ secrets.GHCR_PAT || secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-config-inline: |
          [worker.oci]
            max-parallelism = 1
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ env.OWNER }}
        password: ${{ env.GHCR_TOKEN }}
    # Use the repository information of the checked-out code to format docker tags
    - name: Docker meta
      id: docker_meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_NAME }}
        tag-semver: |
          {{version}}
    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        file: ./Dockerfile.gpu
        platforms: linux/amd64
        push: true
        cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:gpu-buildcache
        cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:gpu-buildcache,mode=max
        build-args: |
          BASE_ODM_IMAGE=${{ env.BASE_ODM_IMAGE }}
        tags: |
          ${{ env.IMAGE_NAME }}:gpu
