name: Publish Docker Intel GPU
env:
  GHCR_OWNER: ${{ vars.GHCR_OWNER || github.repository_owner }}
  GHCR_TOKEN: ${{ secrets.GHCR_PAT || secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
    - master
    tags:
    - v*
  
  # Triggered by ODM build (after docker push)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: ghcr.io/${{ env.GHCR_OWNER }}/nodeodm
      BASE_NODEODM_GPU_IMAGE: ghcr.io/${{ env.GHCR_OWNER }}/nodeodm:gpu
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-config-inline: |
          [worker.oci]
            max-parallelism = 1
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ env.GHCR_OWNER }}
        password: ${{ env.GHCR_TOKEN }}
    # Use the repository information of the checked-out code to format docker tags
    - name: Docker meta
      id: docker_meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_NAME }}
        tag-semver: |
          {{version}}
    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        file: ./Dockerfile.gpu.intel
        platforms: linux/amd64
        push: true
        cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:gpu-intel-buildcache
        cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:gpu-intel-buildcache,mode=max
        build-args: |
          BASE_NODEODM_GPU_IMAGE=${{ env.BASE_NODEODM_GPU_IMAGE }}
        tags: |
          ${{ env.IMAGE_NAME }}:gpu.intel
